{
 "title": "Request and response data",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Response Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_sum[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count{route!~\"/health|/metrics\"}[1m]))",
     "legendFormat": "n° request"
    }
   ]
  },
  {
   "title": "Response time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_ms_bucket[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_ms_bucket[5m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_ms_bucket[5m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_ms_bucket[5m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_ms_bucket[5m]))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}